name: "resnet50"

model:
  module: "BaseModel"
  backbone: "resnet50"
  save_path: "/opt/ml/workspace/checkpoints"

augmentation:
  module: "BaseAugmentation"
  resize: [224, 224]

optimizer:
  type: "AdamW"
  lr: 0.001

scheduler:
  lr_decay_step: 20

loss:
  type: cross_entropy 
  class_weight: [1, 1, 1]

train:
  epochs: 30
  seed: 42
  batch_size: 64
  val_ratio: 0.2
  valid_batch_size: 500
  early_stop_round: 5
  log_interval: 20

dataset:
  module: "MaskSplitByProfileDataset"
  path: "/opt/ml/workspace/input/data/train/images"
  age_split: [30, 60]
  oversampling: True
  oversample_category: age
  oversample_weight: [1, 1, 3]

wandb:
  logging: True
  entity: cv_03
  project: jaehun3
  