python train2.py -c exp_config_1.yaml
python train2.py -c exp_config_2.yaml
python train2.py -c exp_config_3.yaml
python train2.py -c exp_config_4.yaml
python train2.py -c exp_config_5.yaml
python train2.py -c exp_config_6.yaml
python train2.py -c exp_config_7.yaml
python train2.py -c exp_config_8.yaml
python train2.py -c exp_config_9.yaml
python train2.py -c exp_config_10.yaml